name: Crystal CI

on: [push, pull_request]
# push:
#   branches: [ $default-branch ]
# pull_request:
#   branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Crystal Ameba Linter
      uses: crystal-ameba/github-action@v0.2.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
