name: Build and push docs

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: shards install
      - name: Build docs
        run: crystal docs
      - name: Deploy documentation to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
